// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

/*
Package calculatorpb is a generated protocol buffer package.

It is generated from these files:
	calculator/calculatorpb/calculator.proto

It has these top-level messages:
	SumRequest
	SumResponse
	PrimeNumberDecompositionRequest
	PrimeNumberDecompositionResponse
	FindMaximumRequest
	FindMaximumResponse
*/
package calculatorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	FirstNumber  int32 `protobuf:"varint,1,opt,name=first_number,json=firstNumber" json:"first_number,omitempty"`
	SecondNumber int32 `protobuf:"varint,2,opt,name=second_number,json=secondNumber" json:"second_number,omitempty"`
}

func (m *SumRequest) Reset()                    { *m = SumRequest{} }
func (m *SumRequest) String() string            { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()               {}
func (*SumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SumRequest) GetFirstNumber() int32 {
	if m != nil {
		return m.FirstNumber
	}
	return 0
}

func (m *SumRequest) GetSecondNumber() int32 {
	if m != nil {
		return m.SecondNumber
	}
	return 0
}

type SumResponse struct {
	SumResult int32 `protobuf:"varint,1,opt,name=sum_result,json=sumResult" json:"sum_result,omitempty"`
}

func (m *SumResponse) Reset()                    { *m = SumResponse{} }
func (m *SumResponse) String() string            { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()               {}
func (*SumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SumResponse) GetSumResult() int32 {
	if m != nil {
		return m.SumResult
	}
	return 0
}

type PrimeNumberDecompositionRequest struct {
	Number int64 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *PrimeNumberDecompositionRequest) Reset()                    { *m = PrimeNumberDecompositionRequest{} }
func (m *PrimeNumberDecompositionRequest) String() string            { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionRequest) ProtoMessage()               {}
func (*PrimeNumberDecompositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PrimeNumberDecompositionRequest) GetNumber() int64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type PrimeNumberDecompositionResponse struct {
	PrimeFactor int64 `protobuf:"varint,1,opt,name=prime_factor,json=primeFactor" json:"prime_factor,omitempty"`
}

func (m *PrimeNumberDecompositionResponse) Reset()         { *m = PrimeNumberDecompositionResponse{} }
func (m *PrimeNumberDecompositionResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeNumberDecompositionResponse) ProtoMessage()    {}
func (*PrimeNumberDecompositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

func (m *PrimeNumberDecompositionResponse) GetPrimeFactor() int64 {
	if m != nil {
		return m.PrimeFactor
	}
	return 0
}

type FindMaximumRequest struct {
	Number int32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *FindMaximumRequest) Reset()                    { *m = FindMaximumRequest{} }
func (m *FindMaximumRequest) String() string            { return proto.CompactTextString(m) }
func (*FindMaximumRequest) ProtoMessage()               {}
func (*FindMaximumRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *FindMaximumRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type FindMaximumResponse struct {
	Maximum int32 `protobuf:"varint,1,opt,name=maximum" json:"maximum,omitempty"`
}

func (m *FindMaximumResponse) Reset()                    { *m = FindMaximumResponse{} }
func (m *FindMaximumResponse) String() string            { return proto.CompactTextString(m) }
func (*FindMaximumResponse) ProtoMessage()               {}
func (*FindMaximumResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *FindMaximumResponse) GetMaximum() int32 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeNumberDecompositionRequest)(nil), "calculator.PrimeNumberDecompositionRequest")
	proto.RegisterType((*PrimeNumberDecompositionResponse)(nil), "calculator.PrimeNumberDecompositionResponse")
	proto.RegisterType((*FindMaximumRequest)(nil), "calculator.FindMaximumRequest")
	proto.RegisterType((*FindMaximumResponse)(nil), "calculator.FindMaximumResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CalculatorService service

type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimerNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimerNumberDecompositionClient, error)
	FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := grpc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimerNumberDecomposition(ctx context.Context, in *PrimeNumberDecompositionRequest, opts ...grpc.CallOption) (CalculatorService_PrimerNumberDecompositionClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[0], c.cc, "/calculator.CalculatorService/PrimerNumberDecomposition", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimerNumberDecompositionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimerNumberDecompositionClient interface {
	Recv() (*PrimeNumberDecompositionResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimerNumberDecompositionClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimerNumberDecompositionClient) Recv() (*PrimeNumberDecompositionResponse, error) {
	m := new(PrimeNumberDecompositionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *calculatorServiceClient) FindMaximum(ctx context.Context, opts ...grpc.CallOption) (CalculatorService_FindMaximumClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CalculatorService_serviceDesc.Streams[1], c.cc, "/calculator.CalculatorService/FindMaximum", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServiceFindMaximumClient{stream}
	return x, nil
}

type CalculatorService_FindMaximumClient interface {
	Send(*FindMaximumRequest) error
	Recv() (*FindMaximumResponse, error)
	grpc.ClientStream
}

type calculatorServiceFindMaximumClient struct {
	grpc.ClientStream
}

func (x *calculatorServiceFindMaximumClient) Send(m *FindMaximumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumClient) Recv() (*FindMaximumResponse, error) {
	m := new(FindMaximumResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CalculatorService service

type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimerNumberDecomposition(*PrimeNumberDecompositionRequest, CalculatorService_PrimerNumberDecompositionServer) error
	FindMaximum(CalculatorService_FindMaximumServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimerNumberDecomposition_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeNumberDecompositionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimerNumberDecomposition(m, &calculatorServicePrimerNumberDecompositionServer{stream})
}

type CalculatorService_PrimerNumberDecompositionServer interface {
	Send(*PrimeNumberDecompositionResponse) error
	grpc.ServerStream
}

type calculatorServicePrimerNumberDecompositionServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimerNumberDecompositionServer) Send(m *PrimeNumberDecompositionResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _CalculatorService_FindMaximum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CalculatorServiceServer).FindMaximum(&calculatorServiceFindMaximumServer{stream})
}

type CalculatorService_FindMaximumServer interface {
	Send(*FindMaximumResponse) error
	Recv() (*FindMaximumRequest, error)
	grpc.ServerStream
}

type calculatorServiceFindMaximumServer struct {
	grpc.ServerStream
}

func (x *calculatorServiceFindMaximumServer) Send(m *FindMaximumResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *calculatorServiceFindMaximumServer) Recv() (*FindMaximumRequest, error) {
	m := new(FindMaximumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimerNumberDecomposition",
			Handler:       _CalculatorService_PrimerNumberDecomposition_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "FindMaximum",
			Handler:       _CalculatorService_FindMaximum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "calculator/calculatorpb/calculator.proto",
}

func init() { proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4f, 0x32, 0x31,
	0x14, 0x85, 0xdf, 0x81, 0xc0, 0x1b, 0xef, 0x8c, 0x26, 0xd6, 0x04, 0x91, 0x44, 0x81, 0xba, 0x21,
	0x91, 0x00, 0xd1, 0x8d, 0x6e, 0xfd, 0x60, 0xa7, 0x31, 0xc0, 0xca, 0x0d, 0x19, 0x4a, 0x49, 0x9a,
	0x4c, 0xa7, 0x63, 0x3f, 0x8c, 0xf1, 0xcf, 0xf8, 0x57, 0x8d, 0x9d, 0x29, 0x53, 0x82, 0x44, 0x77,
	0x73, 0xcf, 0x3c, 0xf7, 0x9c, 0xde, 0xdb, 0x42, 0x8f, 0xc4, 0x09, 0x31, 0x49, 0xac, 0x85, 0x1c,
	0x96, 0x9f, 0xd9, 0xc2, 0x2b, 0x06, 0x99, 0x14, 0x5a, 0x20, 0x28, 0x15, 0x3c, 0x03, 0x98, 0x1a,
	0x3e, 0xa1, 0xaf, 0x86, 0x2a, 0x8d, 0xba, 0x10, 0xad, 0x98, 0x54, 0x7a, 0x9e, 0x1a, 0xbe, 0xa0,
	0xb2, 0x19, 0x74, 0x82, 0x5e, 0x6d, 0x12, 0x5a, 0xed, 0xc9, 0x4a, 0xe8, 0x1c, 0xf6, 0x15, 0x25,
	0x22, 0x5d, 0x3a, 0xa6, 0x62, 0x99, 0x28, 0x17, 0x73, 0x08, 0xf7, 0x21, 0xb4, 0xae, 0x2a, 0x13,
	0xa9, 0xa2, 0xe8, 0x14, 0x40, 0x19, 0x3e, 0x97, 0x54, 0x99, 0x44, 0x17, 0xa6, 0x7b, 0xca, 0x02,
	0x26, 0xd1, 0xf8, 0x06, 0xda, 0xcf, 0x92, 0x71, 0x9a, 0x37, 0xdf, 0x53, 0x22, 0x78, 0x26, 0x14,
	0xd3, 0x4c, 0xa4, 0xee, 0x60, 0x0d, 0xa8, 0x7b, 0x47, 0xaa, 0x4e, 0x8a, 0x0a, 0x3f, 0x40, 0x67,
	0x77, 0x6b, 0x91, 0xde, 0x85, 0x28, 0xfb, 0x66, 0xe6, 0xab, 0x98, 0x68, 0xe1, 0x1c, 0x42, 0xab,
	0x8d, 0xad, 0x84, 0xfb, 0x80, 0xc6, 0x2c, 0x5d, 0x3e, 0xc6, 0xef, 0x8c, 0x97, 0xdb, 0xd8, 0x0c,
	0xad, 0xad, 0x43, 0x87, 0x70, 0xb4, 0x41, 0x17, 0x39, 0x4d, 0xf8, 0xcf, 0x73, 0xa9, 0xe0, 0x5d,
	0x79, 0xf9, 0x59, 0x81, 0xc3, 0xbb, 0xf5, 0xce, 0xa7, 0x54, 0xbe, 0x31, 0x42, 0xd1, 0x35, 0x54,
	0xa7, 0x86, 0xa3, 0xc6, 0xc0, 0xbb, 0xa0, 0xf2, 0x2e, 0x5a, 0xc7, 0x5b, 0x7a, 0x9e, 0x83, 0xff,
	0xa1, 0x0f, 0x38, 0xb1, 0x53, 0xcb, 0x1f, 0xc6, 0x46, 0x17, 0x7e, 0xdf, 0x2f, 0x7b, 0x6d, 0xf5,
	0xff, 0x06, 0xbb, 0xe4, 0x51, 0x80, 0x66, 0x10, 0x7a, 0xc3, 0xa3, 0x33, 0xdf, 0x60, 0x7b, 0x87,
	0xad, 0xf6, 0xce, 0xff, 0xce, 0xb3, 0x17, 0x8c, 0x82, 0xdb, 0x83, 0x97, 0xc8, 0x7f, 0xb3, 0x8b,
	0xba, 0x7d, 0xa9, 0x57, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x94, 0xa3, 0xf1, 0xbf, 0xd5, 0x02,
	0x00, 0x00,
}
